name 'app_sonarqube'
maintainer 'Abhishek Srivastava'
maintainer_email 'abhishek07887@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures app_sonarqube'
long_description 'Installs/Configures app_sonarqube'
version '0.1.4'
depends 'apt', '~> 2.9.2'
depends 'java', '~> 1.32.0'
depends 'mysql', '~> 5.2.13'
supports 'ubuntu', '= 14.04'
